name: Download Mixcloud MP3 and Commit

on:
  workflow_dispatch:
    inputs:
      mixcloud_url:
        description: 'Mixcloud トラックの URL を入力'
        required: true

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. yt-dlp と ffmpeg をインストール
      - name: Install yt-dlp and ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install -U yt-dlp

      # 3. Mixcloud からタイトルを取得
      - name: Get track title
        id: get_title
        run: |
          TITLE=$(yt-dlp --no-playlist --get-title "${{ github.event.inputs.mixcloud_url }}")
          echo "title=$TITLE" >> $GITHUB_OUTPUT

      # 4. Mixcloud から MP3 をダウンロード
      - name: Download MP3 from Mixcloud
        run: |
          TITLE="${{ steps.get_title.outputs.title }}"
          yt-dlp \
            --no-playlist \
            --extract-audio \
            --audio-format mp3 \
            --output "${TITLE}.%(ext)s" \
            "${{ github.event.inputs.mixcloud_url }}"

      # 5. コミット＆プッシュ
      - name: Commit and push MP3 to repository
        env:
          TITLE: ${{ steps.get_title.outputs.title }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${TITLE}.mp3"
          git commit -m "Add downloaded MP3: ${TITLE}.mp3"
          git push
