# .github/workflows/download-mixcloud-mp3.yml
name: Download Mixcloud Track as MP3 with Cover

on:
  workflow_dispatch:
    inputs:
      mixcloud_url:
        description: 'Mixcloud でダウンロードしたいトラックの URL'
        required: true
      push_to_repo:
        description: '生成した MP3 をリポジトリにコミット＆プッシュする場合は true'
        required: false
        default: 'false'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリをチェックアウト（コミット用に認証情報保持）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. タイトルを取得して出力用に保存
      - name: Extract track title
        id: get_title
        run: |
          TITLE=$(yt-dlp --no-playlist --get-title "${{ github.event.inputs.mixcloud_url }}")
          echo "title=$TITLE" >> $GITHUB_OUTPUT

      # 3. yt-dlp と ffmpeg をインストール
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python3 -m pip install --upgrade pip
          pip install yt-dlp

      # 4. Mixcloud からトラックを MP3 に変換してダウンロード
      - name: Download track as MP3
        run: |
          TITLE="${{ steps.get_title.outputs.title }}"
          yt-dlp --no-playlist \
                 --extract-audio \
                 --audio-format mp3 \
                 --output "${TITLE}.%(ext)s" \
                 "${{ github.event.inputs.mixcloud_url }}"

      # 5. アーティスト画像（サムネイル）をダウンロード
      - name: Download thumbnail
        run: |
          TITLE="${{ steps.get_title.outputs.title }}"
          yt-dlp --no-playlist \
                 --skip-download \
                 --write-thumbnail \
                 --output "${TITLE}.%(ext)s" \
                 "${{ github.event.inputs.mixcloud_url }}"

      # 6. ffmpeg で MP3 にカバーアートを埋め込み
      - name: Embed cover into MP3
        run: |
          TITLE="${{ steps.get_title.outputs.title }}"
          MP3="${TITLE}.mp3"
          IMG=$(ls "${TITLE}".jpg "${TITLE}".png 2>/dev/null | head -n1)
          if [ -z "$IMG" ]; then
            echo "::warning::サムネイルが見つかりません。カバーアートなしでスキップします。"
            cp "$MP3" "${TITLE}-with-cover.mp3"
          else
            ffmpeg -y \
              -i "$MP3" \
              -i "$IMG" \
              -map 0:a -map 1:v \
              -c copy \
              -id3v2_version 3 \
              -metadata:s:v title="Cover" \
              -metadata:s:v comment="Cover (front)" \
              "${TITLE}-with-cover.mp3"
          fi

      # 7. コミット＆プッシュ（オプション）
      - name: Commit & push MP3
        if: github.event.inputs.push_to_repo == 'true'
        env:
          TITLE: ${{ steps.get_title.outputs.title }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${TITLE}-with-cover.mp3" || true
          git commit -m "Add Mixcloud MP3 (${TITLE}-with-cover.mp3)" || echo "No changes to commit"
          git push

      # 8. アーティファクトとしてアップロード（push_to_repo = false のとき）
      - name: Upload MP3 artifact
        if: github.event.inputs.push_to_repo == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.get_title.outputs.title }}
          path: "${{ steps.get_title.outputs.title }}-with-cover.mp3"
          retention-days: 7
